# Generated by Django 6.0.4 on 2026-04-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'youtube_url')},
            },
        ),
    ]
